version: "3.7"
services:
  app:
    image: narirock2/homologtwig:v1
    container_name: homologtwig-app
    restart: unless-stopped
    environment:
        - DB_HOST=192.168.1.29
        - DB_PORT=3306
        - DB_DATABASE=twig
        - DB_USERNAME=root
        - DB_PASSWORD=123456
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - homologtwig

  nginx:
    image: nginx:alpine
    container_name: homologtwig-nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - homologtwig

networks:
  homologtwig:
    driver: bridge
